### ISSUE TITLE
Config not propagating to Consul ?

### ISSUE THREAD

**Issue by iangregsondev** [nest-cloud/nestcloud#20]
Hi,

I managed to get it bootstraping now, but I have a problem that it's trying to connect to 127.0.0.1 for consul but i have the BootModule loaded with my config.yaml.

It is supposed to pick this up right?

Hey is there a slack or discord service for nestcloud - just for future reference?

Here is a capture of the screen

![image](https://user-images.githubusercontent.com/2370364/78451128-d97f1880-7683-11ea-90e4-9d635e07c3ac.png)

**Comment by iangregsondev** [comment]
It should be using 192.168.1.20 ip from the config.yaml

**Comment by iangregsondev** [comment]
The other thing, I am not sure if its correct but on the forRootAsync, the only thing it accepts is a AsyncConsulOptions

```
    static forRoot(options: ConsulOptions): DynamicModule;
    static forRootAsync(options: AsyncConsulOptions): DynamicModule;
```

which only contains "inject", it doesn't contain anything else or inherit from ConsulOptions.

**Comment by miaowing** [comment]
The discoveryHost is your service address, not consul address. This is an config example:

```yaml
consul:
  host: localhost
  port: 8500
service:
  discoveryHost: localhost
  healthCheck:
    timeout: 1s
    interval: 10s
  maxRetry: 5
  retryInterval: 5000
  id: null
  name: nestcloud-starter-service
  port: 8081
```

https://github.com/nest-cloud/nestcloud-consul-starter/blob/1062e71c0dd074bf240d623163c6cc399c21d4ad/src/bootstrap-development.yml
