### ISSUE TITLE
Issue with consul loading correct config in Kubernetes

### ISSUE THREAD

**Issue by juicycleff** [nest-cloud/nestcloud#25]
When I deploy my services on kubernetes, consul keeps loading on port `127.0.0.1:8500` even after updating my consul option in bootstrap.yaml file.

<img width="1179" alt="Screen Shot 2020-04-21 at 13 58 23" src="https://user-images.githubusercontent.com/11243590/79863674-722dcc00-83d8-11ea-9cb3-1c086b8819bb.png">

I'm pinching my hair out. Here is my config.yaml

```yaml
consul:
  host: consul-server-bootstrap
  port: 8500
config:
  key: ${{ service.name }}
service:
  discoveryHost: services-tenant.default.svc.cluster.local
  healthCheck:
    timeout: 1s
    interval: 10s
    tcp: ${{ service.discoveryHost }}:${{ service.port }}
  maxRetry: 5
  retryInterval: 5000
  name: service
  port: 50090
loadbalance:
  ruleCls: RandomRule
logger:
  level: info
  transports:
    - transport: console
      colorize: true
      datePattern: YYYY-MM-DD h:mm:ss
      label: ${{ service.name }}

```

Please any help would be great
